site_name: Diy Arduino Gimbal
site_url: 'https://thenoobinventor.github.io/arduino-gimbal/'
use_directory_urls: False
edit_uri: ""

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo 
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - toc.integrate
repo_url: https://github.com/TheNoobInventor/arduino-gimbal
repo_name: TheNoobInventor/arduino-gimbal
plugins:
  - search:
      lang: en
